name: Nix Flake Check

on:
  pull_request:
    branches:
      - '**'

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30

      - name: Run nix flake check
        run: nix flake check

